spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:postgresql://switchyard.proxy.rlwy.net:53676/railway
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080